### ISSUE TITLE
create registration pages

### ISSUE THREAD

**Issue by martinwachira** [martinwachira/fundilink-client#3]

**Comment by thePlebDev** [comment]
is this still up for grabs. if so, please assign me to it. Thank you

**Comment by martinwachira** [comment]
*Hi Elliot,*

Do you have a grasp of what this project is about?


*Martin Wachira*
Phone: +254705112077

**Comment by thePlebDev** [comment]
yes, I believe so. Just to be clear, you want a registration page created with react, correct?

**Comment by martinwachira** [comment]
Yes, for two users based on the role selected, I want to have a drop down option, select whether a user is a service provider or an employer and based on the  respectively different registration forms is displayed, because I'm capturing different type of data for both users.

**Comment by martinwachira** [comment]
Like for example, if I select a service provider, then I get a form with like 4 fields, and if I select an employer I get a registration form with 5 fields.

**Comment by thePlebDev** [comment]
is, it possible for you to upload an mock up of the design. That would help a lot. Just the bare minimum

**Comment by thePlebDev** [comment]
but I will be able to build some basic forms with simple client side validation and give them for you to review

**Comment by martinwachira** [comment]
Okay, sorry I wasn't able to upload the wireframes. But it's okay, just go ahead
I'm using adminlte for UI

**Comment by martinwachira** [comment]
I merged your changes

**Comment by thePlebDev** [comment]
so what css framework should I build the form in? sass? adminlte-react? adminlte?

**Comment by martinwachira** [comment]
adminlte
